node {
	stage ('Build') {
       echo 'Building..'
       withMaven(
        maven: 'M3',
        mavenSettingsConfig: 'my-maven-settings',
        mavenLocalRepo: '.repository') {
      	sh 'mvn --version'
    	}
  	}
  	
  	stage('Test') {
        echo 'Testing..'
    }
}