node {
	echo 'Hello world'
	
	stage ('Build') {

    //git url: 'https://github.com/Techolution/techo-leagues.git'

    withMaven(
        maven: 'M3',
        mavenSettingsConfig: 'my-maven-settings',
        mavenLocalRepo: '.repository') {
        echo 'Starting Build!'
      	sh "mvn clean install"
      	echo 'Build Complete!'
    	} 
  	}
}